# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            adrian li
tagline:          'a seeker of shortcuts'
description:      'an overeducated underachieving human, just trying to be a little less sucky every day'
url:              http://adrianmcli.com
baseurl:          /

author:
  name:           'Adrian Li'
  url:            https://adrianmcli.com

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
