# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            adrian
tagline:          'a seeker of shortcuts'
description:      "tracking my days on Earth, I'll make another blog when I leave here"
url:              http://adrianmcli.com
baseurl:          /

author:
  name:           'Adrian Li'
  url:            https://adrianmcli.com

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/adrianmc
