# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            adrian
tagline:          'seeker of shortcuts'
description:      "just trying to make my way through life"
url:              http://adrianmcli.com
baseurl:          /

author:
  name:           'Adrian Li'
  url:            https://adrianmcli.com

paginate:         5

# Custom vars
version:          1.0

github:
  repo:           https://github.com/adrianmc
